BEGIN;
--
-- Create model User
--
CREATE TABLE "users_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "cedula" varchar(20) NOT NULL UNIQUE, "telefono" varchar(15) NULL, "cargo" varchar(50) NULL, "empresa" varchar(100) NULL);
CREATE TABLE "users_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);  
CREATE TABLE "users_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE INDEX "users_user_username_06e46fe6_like" ON "users_user" ("username" varchar_pattern_ops);
CREATE INDEX "users_user_email_243f6e77_like" ON "users_user" ("email" varchar_pattern_ops);
CREATE INDEX "users_user_cedula_7880d384_like" ON "users_user" ("cedula" varchar_pattern_ops);
ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_group_id_b88eab82_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_5f6f5a90_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_group_id_9afc8d0e_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_user_groups_user_id_5f6f5a90" ON "users_user_groups" ("user_id");
CREATE INDEX "users_user_groups_group_id_9afc8d0e" ON "users_user_groups" ("group_id");
ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_permission_id_43338c45_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_20aca447_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_perm_permission_id_0b93982e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_user_user_permissions_user_id_20aca447" ON "users_user_user_permissions" ("user_id");
CREATE INDEX "users_user_user_permissions_permission_id_0b93982e" ON "users_user_user_permissions" ("permission_id");
COMMIT;



(venv) PS C:\Users\JOHN FORERO\Documents\erp_Colombiano\ERP_COLOMBIANO_BACKEND> python manage.py migrate
(0.004) 
            SELECT
                c.relname,
                CASE
                    WHEN c.relispartition THEN 'p'
                    WHEN c.relkind IN ('m', 'v') THEN 'v'
                    ELSE 't'
                END,
                obj_description(c.oid, 'pg_class')
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid)
        ; args=None; alias=default
(0.001) 
            SELECT
                c.relname,
                CASE
                    WHEN c.relispartition THEN 'p'
                    WHEN c.relkind IN ('m', 'v') THEN 'v'
                    ELSE 't'
                END,
                obj_description(c.oid, 'pg_class')
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid)
        ; args=None; alias=default
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, sessions, users
Running migrations:
(0.001)
            SELECT
                c.relname,
                CASE
                    WHEN c.relispartition THEN 'p'
                    WHEN c.relkind IN ('m', 'v') THEN 'v'
                    ELSE 't'
                END,
                obj_description(c.oid, 'pg_class')
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid)
        ; args=None; alias=default
(0.000) BEGIN; args=None; alias=default
CREATE TABLE "django_migrations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL); (params None)
(0.442) CREATE TABLE "django_migrations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL); args=None; alias=default
(0.002) COMMIT; args=None; alias=default
  Applying contenttypes.0001_initial...(0.000) BEGIN; args=None; alias=default
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL); (params None)
(0.003) CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL); args=None; alias=default
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model"); (params None)
(0.015) ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model"); args=None; alias=default
(0.006)
            SELECT
                c.relname,
                CASE
                    WHEN c.relispartition THEN 'p'
                    WHEN c.relkind IN ('m', 'v') THEN 'v'
                    ELSE 't'
                END,
                obj_description(c.oid, 'pg_class')
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid)
        ; args=None; alias=default
(0.005) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('contenttypes', '0001_initial', '2026-03-10T02:19:31.798204+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('contenttypes', '0001_initial', datetime.datetime(2026, 3, 10, 2, 19, 31, 798204, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying contenttypes.0002_remove_content_type_name...(0.000) BEGIN; args=None; alias=default
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL; (params None)
(0.002) ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL; args=None; alias=default
ALTER TABLE "django_content_type" DROP COLUMN "name"; (params None)
(0.001) ALTER TABLE "django_content_type" DROP COLUMN "name"; args=None; alias=default
(0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('contenttypes', '0002_remove_content_type_name', '2026-03-10T02:19:31.814035+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('contenttypes', '0002_remove_content_type_name', datetime.datetime(2026, 3, 10, 2, 19, 31, 814035, tzinfo=datetime.timezone.utc)); alias=default
(0.000) COMMIT; args=None; alias=default
 OK
  Applying auth.0001_initial...(0.000) BEGIN; args=None; alias=default
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL); (params None)
(0.004) CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL); args=None; alias=default
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE); (params None)
(0.006) CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE); args=None; alias=default
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL); (params None)
(0.003) CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL); args=None; alias=default
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename"); (params None)    
(0.002) ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename"); args=None; alias=default
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED; (params None)
(0.010) ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED; args=None; alias=default
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id"); (params None)
(0.003) CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id"); args=None; alias=default
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops); (params None)
(0.002) CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops); args=None; alias=default
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id"); (params None)
(0.015) ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id"); args=None; alias=default
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED; (params None)
(0.006) ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED; args=None; alias=default
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED; (params None)
(0.002) ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED; args=None; alias=default
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id"); (params None)
(0.001) CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id"); args=None; alias=default
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id"); (params None)
(0.002) CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id"); args=None; alias=default
(0.001) COMMIT; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0001_initial', '2026-03-10T02:19:31.893771+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0001_initial', datetime.datetime(2026, 3, 10, 2, 19, 31, 893771, tzinfo=datetime.timezone.utc)); alias=default
 OK
  Applying auth.0002_alter_permission_name_max_length...(0.000) BEGIN; args=None; alias=default
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255); (params None)
(0.001) ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255); args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0002_alter_permission_name_max_length', '2026-03-10T02:19:31.900142+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0002_alter_permission_name_max_length', datetime.datetime(2026, 3, 10, 2, 19, 31, 900142, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying auth.0003_alter_user_email_max_length...(0.000) BEGIN; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0003_alter_user_email_max_length', '2026-03-10T02:19:31.907561+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0003_alter_user_email_max_length', datetime.datetime(2026, 3, 10, 2, 19, 31, 907561, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying auth.0004_alter_user_username_opts...(0.000) BEGIN; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0004_alter_user_username_opts', '2026-03-10T02:19:31.916332+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0004_alter_user_username_opts', datetime.datetime(2026, 3, 10, 2, 19, 31, 916332, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying auth.0005_alter_user_last_login_null...(0.000) BEGIN; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0005_alter_user_last_login_null', '2026-03-10T02:19:31.927252+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0005_alter_user_last_login_null', datetime.datetime(2026, 3, 10, 2, 19, 31, 927252, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying auth.0006_require_contenttypes_0002...(0.000) BEGIN; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0006_require_contenttypes_0002', '2026-03-10T02:19:31.930662+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0006_require_contenttypes_0002', datetime.datetime(2026, 3, 10, 2, 19, 31, 930662, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying auth.0007_alter_validators_add_error_messages...(0.000) BEGIN; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0007_alter_validators_add_error_messages', '2026-03-10T02:19:31.937950+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0007_alter_validators_add_error_messages', datetime.datetime(2026, 3, 10, 2, 19, 31, 937950, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying auth.0008_alter_user_username_max_length...(0.000) BEGIN; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0008_alter_user_username_max_length', '2026-03-10T02:19:31.951435+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0008_alter_user_username_max_length', datetime.datetime(2026, 3, 10, 2, 19, 31, 951435, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying auth.0009_alter_user_last_name_max_length...(0.000) BEGIN; args=None; alias=default
(0.002) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0009_alter_user_last_name_max_length', '2026-03-10T02:19:31.960243+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0009_alter_user_last_name_max_length', datetime.datetime(2026, 3, 10, 2, 19, 31, 960243, tzinfo=datetime.timezone.utc)); alias=default
(0.002) COMMIT; args=None; alias=default
 OK
  Applying auth.0010_alter_group_name_max_length...(0.000) BEGIN; args=None; alias=default
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150); (params None)
(0.144) ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150); args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0010_alter_group_name_max_length', '2026-03-10T02:19:32.118721+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0010_alter_group_name_max_length', datetime.datetime(2026, 3, 10, 2, 19, 32, 118721, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying auth.0011_update_proxy_permissions...(0.000) BEGIN; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0011_update_proxy_permissions', '2026-03-10T02:19:32.137785+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0011_update_proxy_permissions', datetime.datetime(2026, 3, 10, 2, 19, 32, 137785, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying auth.0012_alter_user_first_name_max_length...(0.000) BEGIN; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0012_alter_user_first_name_max_length', '2026-03-10T02:19:32.158772+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('auth', '0012_alter_user_first_name_max_length', datetime.datetime(2026, 3, 10, 2, 19, 32, 158772, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying users.0001_initial...(0.000) BEGIN; args=None; alias=default
CREATE TABLE "users_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "cedula" varchar(20) NOT NULL UNIQUE, "telefono" varchar(15) NULL, "cargo" varchar(50) NULL, "empresa" varchar(100) NULL); (params None)
(0.013) CREATE TABLE "users_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "cedula" varchar(20) NOT NULL UNIQUE, "telefono" varchar(15) NULL, "cargo" varchar(50) NULL, "empresa" varchar(100) NULL); args=None; alias=default
CREATE TABLE "users_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL); (params None)
(0.004) CREATE TABLE "users_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL); args=None; alias=default
CREATE TABLE "users_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL); (params None)
(0.003) CREATE TABLE "users_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL); args=None; alias=default
CREATE INDEX "users_user_username_06e46fe6_like" ON "users_user" ("username" varchar_pattern_ops); (params None)
(0.001) CREATE INDEX "users_user_username_06e46fe6_like" ON "users_user" ("username" varchar_pattern_ops); args=None; alias=default
CREATE INDEX "users_user_email_243f6e77_like" ON "users_user" ("email" varchar_pattern_ops); (params None)
(0.001) CREATE INDEX "users_user_email_243f6e77_like" ON "users_user" ("email" varchar_pattern_ops); args=None; alias=default
CREATE INDEX "users_user_cedula_7880d384_like" ON "users_user" ("cedula" varchar_pattern_ops); (params None)
(0.001) CREATE INDEX "users_user_cedula_7880d384_like" ON "users_user" ("cedula" varchar_pattern_ops); args=None; alias=default
ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_group_id_b88eab82_uniq" UNIQUE ("user_id", "group_id"); (params None)
(0.002) ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_group_id_b88eab82_uniq" UNIQUE ("user_id", "group_id"); args=None; alias=default
ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_5f6f5a90_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED; (params None)
(0.009) ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_5f6f5a90_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED; args=None; alias=default
ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_group_id_9afc8d0e_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED; (params None)
(0.003) ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_group_id_9afc8d0e_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED; args=None; alias=default
CREATE INDEX "users_user_groups_user_id_5f6f5a90" ON "users_user_groups" ("user_id"); (params None)
(0.001) CREATE INDEX "users_user_groups_user_id_5f6f5a90" ON "users_user_groups" ("user_id"); args=None; alias=default
CREATE INDEX "users_user_groups_group_id_9afc8d0e" ON "users_user_groups" ("group_id"); (params None)
(0.001) CREATE INDEX "users_user_groups_group_id_9afc8d0e" ON "users_user_groups" ("group_id"); args=None; alias=default
ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_permission_id_43338c45_uniq" UNIQUE ("user_id", "permission_id"); (params None)
(0.002) ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_permission_id_43338c45_uniq" UNIQUE ("user_id", "permission_id"); args=None; alias=default
ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_20aca447_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED; (params None)
(0.002) ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_20aca447_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED; args=None; alias=default
ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_perm_permission_id_0b93982e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED; (params None)
(0.002) ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_perm_permission_id_0b93982e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED; args=None; alias=default
CREATE INDEX "users_user_user_permissions_user_id_20aca447" ON "users_user_user_permissions" ("user_id"); (params None)
(0.001) CREATE INDEX "users_user_user_permissions_user_id_20aca447" ON "users_user_user_permissions" ("user_id"); args=None; alias=default
CREATE INDEX "users_user_user_permissions_permission_id_0b93982e" ON "users_user_user_permissions" ("permission_id"); (params None)
(0.001) CREATE INDEX "users_user_user_permissions_permission_id_0b93982e" ON "users_user_user_permissions" ("permission_id"); args=None; alias=default
(0.002) COMMIT; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('users', '0001_initial', '2026-03-10T02:19:32.238158+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('users', '0001_initial', datetime.datetime(2026, 3, 10, 2, 19, 32, 238158, tzinfo=datetime.timezone.utc)); alias=default       
 OK
  Applying admin.0001_initial...(0.000) BEGIN; args=None; alias=default
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" bigint NOT NULL); (params None)
(0.035) CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" bigint NOT NULL); args=None; alias=default
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED; (params None)
(0.002) ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED; args=None; alias=default
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED; (params None)
(0.003) ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED; args=None; alias=default
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id"); (params None)
(0.003) CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id"); args=None; alias=default
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id"); (params None)
(0.001) CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id"); args=None; alias=default
(0.001) COMMIT; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('admin', '0001_initial', '2026-03-10T02:19:32.297082+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('admin', '0001_initial', datetime.datetime(2026, 3, 10, 2, 19, 32, 297082, tzinfo=datetime.timezone.utc)); alias=default       
 OK
  Applying admin.0002_logentry_remove_auto_add...(0.000) BEGIN; args=None; alias=default
(0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('admin', '0002_logentry_remove_auto_add', '2026-03-10T02:19:32.302895+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('admin', '0002_logentry_remove_auto_add', datetime.datetime(2026, 3, 10, 2, 19, 32, 302895, tzinfo=datetime.timezone.utc)); alias=default
(0.000) COMMIT; args=None; alias=default
 OK
  Applying admin.0003_logentry_add_action_flag_choices...(0.000) BEGIN; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('admin', '0003_logentry_add_action_flag_choices', '2026-03-10T02:19:32.311583+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('admin', '0003_logentry_add_action_flag_choices', datetime.datetime(2026, 3, 10, 2, 19, 32, 311583, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying authtoken.0001_initial...(0.000) BEGIN; args=None; alias=default
CREATE TABLE "authtoken_token" ("key" varchar(40) NOT NULL PRIMARY KEY, "created" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL UNIQUE); (params None)
(0.005) CREATE TABLE "authtoken_token" ("key" varchar(40) NOT NULL PRIMARY KEY, "created" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL UNIQUE); args=None; alias=default
ALTER TABLE "authtoken_token" ADD CONSTRAINT "authtoken_token_user_id_35299eff_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED; (params None)
(0.003) ALTER TABLE "authtoken_token" ADD CONSTRAINT "authtoken_token_user_id_35299eff_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED; args=None; alias=default
CREATE INDEX "authtoken_token_key_10f0b77e_like" ON "authtoken_token" ("key" varchar_pattern_ops); (params None)
(0.001) CREATE INDEX "authtoken_token_key_10f0b77e_like" ON "authtoken_token" ("key" varchar_pattern_ops); args=None; alias=default
(0.001) COMMIT; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('authtoken', '0001_initial', '2026-03-10T02:19:32.335400+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('authtoken', '0001_initial', datetime.datetime(2026, 3, 10, 2, 19, 32, 335400, tzinfo=datetime.timezone.utc)); alias=default
 OK
  Applying authtoken.0002_auto_20160226_1747...(0.000) BEGIN; args=None; alias=default
(0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('authtoken', '0002_auto_20160226_1747', '2026-03-10T02:19:32.373443+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('authtoken', '0002_auto_20160226_1747', datetime.datetime(2026, 3, 10, 2, 19, 32, 373443, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying authtoken.0003_tokenproxy...(0.000) BEGIN; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('authtoken', '0003_tokenproxy', '2026-03-10T02:19:32.378605+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('authtoken', '0003_tokenproxy', datetime.datetime(2026, 3, 10, 2, 19, 32, 378605, tzinfo=datetime.timezone.utc)); alias=default
(0.001) COMMIT; args=None; alias=default
 OK
  Applying authtoken.0004_alter_tokenproxy_options...(0.000) BEGIN; args=None; alias=default
(0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('authtoken', '0004_alter_tokenproxy_options', '2026-03-10T02:19:32.384943+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('authtoken', '0004_alter_tokenproxy_options', datetime.datetime(2026, 3, 10, 2, 19, 32, 384943, tzinfo=datetime.timezone.utc)); alias=default
(0.000) COMMIT; args=None; alias=default
 OK
  Applying sessions.0001_initial...(0.000) BEGIN; args=None; alias=default
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL); (params None)
(0.003) CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL); args=None; alias=default
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops); (params None)
(0.002) CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops); args=None; alias=default
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date"); (params None)
(0.002) CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date"); args=None; alias=default
(0.001) COMMIT; args=None; alias=default
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('sessions', '0001_initial', '2026-03-10T02:19:32.398004+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('sessions', '0001_initial', datetime.datetime(2026, 3, 10, 2, 19, 32, 398004, tzinfo=datetime.timezone.utc)); alias=default 
 OK
(0.000) SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations"; args=(); alias=default
(0.002) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',); alias=default
(0.003) INSERT INTO "django_content_type" ("app_label", "model") VALUES ('admin', 'logentry') RETURNING "django_content_type"."id"; args=('admin', 'logentry'); alias=default
(0.001) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'admin' AND "django_content_type"."model" IN ('logentry')); args=('admin', 'logentry'); alias=default
(0.001) SELECT "auth_permission"."content_type_id" AS "content_type", "auth_permission"."codename" AS "codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (1) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, 2 ASC; args=(1,); alias=default
(0.003) INSERT INTO "auth_permission" ("name", "content_type_id", "codename") SELECT * FROM UNNEST((ARRAY['Can add log entry','Can change log entry','Can delete log entry','Can view log entry'])::varchar[], (ARRAY[1,1,1,1])::integer[], (ARRAY['add_logentry','change_logentry','delete_logentry','view_logentry'])::varchar[]) RETURNING "auth_permission"."id"; args=(['Can add log entry', 'Can change log entry', 'Can delete log entry', 'Can view log entry'], [1, 1, 1, 1], ['add_logentry', 'change_logentry', 'delete_logentry', 'view_logentry']); alias=default
(0.001) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',); alias=default
(0.000) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',); alias=default
(0.001) INSERT INTO "django_content_type" ("app_label", "model") SELECT * FROM UNNEST((ARRAY['auth','auth'])::varchar[], (ARRAY['group','permission'])::varchar[]) RETURNING "django_content_type"."id"; args=(['auth', 'auth'], ['group', 'permission']); alias=default
(0.001) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" IN ('permission', 'group')); args=('auth', 'permission', 'group'); alias=default
(0.001) SELECT "auth_permission"."content_type_id" AS "content_type", "auth_permission"."codename" AS "codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (2, 3) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, 2 ASC; args=(2, 3); alias=default
(0.001) INSERT INTO "auth_permission" ("name", "content_type_id", "codename") SELECT * FROM UNNEST((ARRAY['Can add permission','Can change permission','Can delete permission','Can view permission','Can add group','Can change group','Can delete group','Can view group'])::varchar[], (ARRAY[3,3,3,3,2,2,2,2])::integer[], (ARRAY['add_permission','change_permission','delete_permission','view_permission','add_group','change_group','delete_group','view_group'])::varchar[]) RETURNING "auth_permission"."id"; args=(['Can add permission', 'Can change permission', 'Can delete permission', 'Can view permission', 'Can add group', 'Can change group', 'Can delete group', 'Can view group'], [3, 3, 3, 3, 2, 2, 2, 2], ['add_permission', 'change_permission', 'delete_permission', 'view_permission', 'add_group', 'change_group', 'delete_group', 'view_group']); alias=default
(0.000) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',); alias=default
(0.000) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',); alias=default
(0.000) INSERT INTO "django_content_type" ("app_label", "model") VALUES ('contenttypes', 'contenttype') RETURNING "django_content_type"."id"; args=('contenttypes', 'contenttype'); alias=default
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'contenttypes' AND "django_content_type"."model" IN ('contenttype')); args=('contenttypes', 'contenttype'); alias=default
(0.001) SELECT "auth_permission"."content_type_id" AS "content_type", "auth_permission"."codename" AS "codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (4) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, 2 ASC; args=(4,); alias=default
(0.002) INSERT INTO "auth_permission" ("name", "content_type_id", "codename") SELECT * FROM UNNEST((ARRAY['Can add content type','Can change content type','Can delete content type','Can view content type'])::varchar[], (ARRAY[4,4,4,4])::integer[], (ARRAY['add_contenttype','change_contenttype','delete_contenttype','view_contenttype'])::varchar[]) RETURNING "auth_permission"."id"; args=(['Can add content type', 'Can change content type', 'Can delete content type', 'Can view content type'], [4, 4, 4, 4], ['add_contenttype', 'change_contenttype', 'delete_contenttype', 'view_contenttype']); alias=default
(0.002) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',); alias=default
(0.001) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',); alias=default
(0.001) INSERT INTO "django_content_type" ("app_label", "model") VALUES ('sessions', 'session') RETURNING "django_content_type"."id"; args=('sessions', 'session'); alias=default
(0.001) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'sessions' AND "django_content_type"."model" IN ('session')); args=('sessions', 'session'); alias=default
(0.001) SELECT "auth_permission"."content_type_id" AS "content_type", "auth_permission"."codename" AS "codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (5) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, 2 ASC; args=(5,); alias=default
(0.003) INSERT INTO "auth_permission" ("name", "content_type_id", "codename") SELECT * FROM UNNEST((ARRAY['Can add session','Can change session','Can delete session','Can view session'])::varchar[], (ARRAY[5,5,5,5])::integer[], (ARRAY['add_session','change_session','delete_session','view_session'])::varchar[]) RETURNING "auth_permission"."id"; args=(['Can add session', 'Can change session', 'Can delete session', 'Can view session'], [5, 5, 5, 5], ['add_session', 'change_session', 'delete_session', 'view_session']); alias=default
(0.001) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',); alias=default
(0.001) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'authtoken'; args=('authtoken',); alias=default
(0.001) INSERT INTO "django_content_type" ("app_label", "model") SELECT * FROM UNNEST((ARRAY['authtoken','authtoken'])::varchar[], (ARRAY['token','tokenproxy'])::varchar[]) RETURNING "django_content_type"."id"; args=(['authtoken', 'authtoken'], ['token', 'tokenproxy']); alias=default
(0.001) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'authtoken' AND "django_content_type"."model" IN ('tokenproxy', 'token')); args=('authtoken', 'tokenproxy', 'token'); alias=default
(0.001) SELECT "auth_permission"."content_type_id" AS "content_type", "auth_permission"."codename" AS "codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (6, 7) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, 2 ASC; args=(6, 7); alias=default
(0.001) INSERT INTO "auth_permission" ("name", "content_type_id", "codename") SELECT * FROM UNNEST((ARRAY['Can add Token','Can change Token','Can delete Token','Can view Token','Can add Token','Can change Token','Can delete Token','Can view Token'])::varchar[], (ARRAY[6,6,6,6,7,7,7,7])::integer[], (ARRAY['add_token','change_token','delete_token','view_token','add_tokenproxy','change_tokenproxy','delete_tokenproxy','view_tokenproxy'])::varchar[]) RETURNING "auth_permission"."id"; args=(['Can add Token', 'Can change Token', 'Can delete Token', 'Can view Token', 'Can add Token', 'Can change Token', 'Can delete Token', 'Can view Token'], [6, 6, 6, 6, 7, 7, 7, 7], ['add_token', 'change_token', 'delete_token', 'view_token', 'add_tokenproxy', 'change_tokenproxy', 'delete_tokenproxy', 'view_tokenproxy']); alias=default
(0.002) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'authtoken'; args=('authtoken',); alias=default
(0.001) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'users'; args=('users',); alias=default
(0.001) INSERT INTO "django_content_type" ("app_label", "model") VALUES ('users', 'user') RETURNING "django_content_type"."id"; args=('users', 'user'); alias=default
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'users' AND "django_content_type"."model" IN ('user')); args=('users', 'user'); alias=default
(0.001) SELECT "auth_permission"."content_type_id" AS "content_type", "auth_permission"."codename" AS "codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (8) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, 2 ASC; args=(8,); alias=default
(0.001) INSERT INTO "auth_permission" ("name", "content_type_id", "codename") SELECT * FROM UNNEST((ARRAY['Can add user','Can change user','Can delete user','Can view user'])::varchar[], (ARRAY[8,8,8,8])::integer[], (ARRAY['add_user','change_user','delete_user','view_user'])::varchar[]) RETURNING "auth_permission"."id"; args=(['Can add user', 'Can change user', 'Can delete user', 'Can view user'], [8, 8, 8, 8], ['add_user', 'change_user', 'delete_user', 'view_user']); alias=default
(0.000) SELECT "django_content_type"."model" AS "model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'users'; args=('users',); alias=default