# Generated by Django 6.0.3 on 2026-06-04 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('iso_code_3', models.CharField(max_length=3, unique=True, verbose_name='Nomenclatura ISO3')),
                ('phone_code', models.CharField(max_length=5, verbose_name='Prefijo Telefónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=10, unique=True, verbose_name='Código de Departamento')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Departamento / Estado',
                'verbose_name_plural': 'Departamentos / Estados',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=15, unique=True, verbose_name='Código de Ciudad')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.state', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
    ]
