# Generated by Django 6.0.3 on 2026-06-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True, verbose_name='Estado Activo'),
        ),
    ]
