# Generated by Django 6.0.3 on 2026-04-08 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del permiso')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Código Interno')),
            ],
            options={
                'verbose_name': 'Permiso de Inquilino',
                'verbose_name_plural': 'Permisos de Inquilinos',
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Usuario Inquilino',
                'verbose_name_plural': 'Usuarios Inquilinos',
            },
        ),
        migrations.CreateModel(
            name='TenantRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Rol')),
                ('permission', models.ManyToManyField(blank=True, to='tenant_users.tenantpermission', verbose_name='Permisos Asignados')),
            ],
            options={
                'verbose_name': 'Rol de Inquilino',
                'verbose_name_plural': 'Roles de Inquilinos',
            },
        ),
    ]
