"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config, Csv 
from datetime import timedelta # <--- Necesario para medir tiempos



# ------------------------ 1. CONFIGURACIÓN DE RUTAS -----------------------

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# ------------------------ 2. SEGURIDAD Y ENTORNO ----------------------------

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())


# Interruptor Maestro de Seguridad (SSL/HTTPS) (Viene del .env) 
# Si es False, permite pruebas por IP/HTTP. Si es True, exige HTTPS.
USE_HTTPS = config('USE_HTTPS', default=False, cast=bool)

# Seguridad de Cookies y Red
SESSION_COOKIE_HTTPONLY = True  # Protege contra robo de sesión por JS (XSS)
SESSION_COOKIE_SECURE = USE_HTTPS # Las cookies de sesión solo viajan por canales seguros (HTTPS)
CSRF_COOKIE_SECURE = USE_HTTPS  # Protege los formularios contra ataques de falsificación
SECURE_SSL_REDIRECT = USE_HTTPS  # Redirige automáticamente HTTP a HTTPS si es True



#  ------------------------ 3. DEFINICIÓN DE APLICACIONES  ------------------------

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

     # ... otras aplicaciones ...
    'drf_spectacular',

     # --- TERCEROS ---
    'rest_framework',
    'rest_framework.authtoken',  # Requerida por dj-rest-auth
    'dj_rest_auth',              # Gestionar autenticacion
    'rest_framework_simplejwt',  # Seguridad JWT
    'corsheaders',               # Permisos de conexión (CORS)
    
    # --- APPS ---
    # --- DOMINIO ADMINISTRATIVO ---
    'apps.admin.admin_users',
    
    # --- DOMINIO INQUILINOS (NEGOCIO) ---
    'apps.tenant.tenant_users',
]



# ----------------------------  4. MIDDLEWARE (Orden Crítico) ---------------------------- 

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]




# --------------------- 5. NÚCLEO DE DJANGO (URLS, TEMPLATES, WSGI) ----------------------

ROOT_URLCONF = 'core.urls'
WSGI_APPLICATION = 'core.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



# --------------------------- 6. BASE DE DATOS Y ENRUTAMIENTO ---------------------------

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME_DEFAULT'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    },
    'tenant': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME_TENANT'),
        'USER': config('DB_USER_TENANT', default=config('DB_USER')), 
        'PASSWORD': config('DB_PASSWORD_TENANT', default=config('DB_PASSWORD')),
        'HOST': config('DB_HOST_TENANT', default=config('DB_HOST')),
        'PORT': config('DB_PORT_TENANT', default=config('DB_PORT')),
    }
}

# Enrutador de tráfico para separar la data administrativa de la del negocio
DATABASE_ROUTERS = ['core.routers.ErpDatabaseRouter']



# --------------------------- 7. AUTENTICACIÓN Y MODELO DE USUARIO ---------------------------

# --- CONFIGURACIÓN DEL MODELO DE USUARIO MAESTRO ---
# Le indicamos al framework que el motor de autenticación debe usar 
# nuestra clase personalizada en lugar del usuario por defecto.
AUTH_USER_MODEL = 'admin_users.AdminUser'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --- CONFIGURACIÓN DE SISTEMAS DE AUTENTICACIÓN ---
AUTHENTICATION_BACKENDS = [
    # 1. Tu nuevo Escáner Híbrido (ajusta la ruta según el nombre de tu app)
    'apps.users.backends.EmailOrUsernameModelBackend',
    
    # 2. El sistema estándar de Django (mantenido como respaldo)
    'django.contrib.auth.backends.ModelBackend',
]

# Configuración adicional de cuenta (AllAuth/Auth logic)

# Método de autenticación: 'username_email' permite AMBOS.
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  
# El correo es obligatorio y no se puede repetir en la base de datos.
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
# El username sigue siendo requerido para la base de datos interna
ACCOUNT_USERNAME_REQUIRED = True 
# Evita que pida confirmación de email por correo (útil para pruebas locales).
# Se activa cuando se haya configurado un servidor de correos (SMTP).
ACCOUNT_EMAIL_VERIFICATION = 'none'




# --------------------------- 8. DJANGO REST FRAMEWORK (DRF) ---------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv())



# ---------------------- 9. CONFIGURACIÓN JWT DE TOKENS (SimpleJWT) ------------------------

# Define el comportamiento y duración de las llaves digitales para la API.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # El carnet de acceso dura 1 hora
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    # La llave de repuesto dura 1 día
    'ROTATE_REFRESH_TOKENS': True,                  # Genera una nueva llave maestra cada vez que se usa
    'ALGORITHM': 'HS256',                           # Algoritmo estándar de cifrado
    'SIGNING_KEY': SECRET_KEY,                      # Firma los tokens con la llave secreta del proyecto
    'AUTH_HEADER_TYPES': ('Bearer',),               # Prefijo que exigirá Postman/React: 'Bearer <token>'
}



# --------------- 10. CONFIGURACIÓN DE DOCUMENTACIÓN (Swagger/Spectacular) -------------

SPECTACULAR_SETTINGS = {
    'TITLE': 'ERP Colombiano API',
    'DESCRIPTION': 'Documentación interactiva de los servicios del ERP. Incluye gestión de usuarios y autenticación JWT.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Permite que la documentación use el botón de "Authorize" con Tokens JWT
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_SPLIT_REQUEST': True,
}



# --------------------- 11. ARCHIVOS ESTÁTICOS E INTERNACIONALIZACIÓN ---------------------------

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Carpeta física donde se recolectarán todos los archivos (Ruta absoluta)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')



# ------------------------ 12. LOGGING (Solo en Desarrollo) ---------------------------

# Habilita poder visualizar cada instrucción SQL que Django envía a PostgreSQL mientras el servidor está corriendo 
if DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django.db.backends': {
                'level': 'DEBUG',
                'handlers': ['console'],
            },
        },
    }
