# Generated by Django 6.0.3 on 2026-06-10 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_geography', '0002_alter_city_is_active_alter_country_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type_code', models.CharField(max_length=10, null=True, unique=True, verbose_name='Codigo legal')),
                ('abbreviation', models.CharField(max_length=15, null=True, unique=True, verbose_name='Nomenclatura')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(db_default=True, default=True, verbose_name='Estado Activo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Tipo de identificación',
                'verbose_name_plural': 'Tipos de identificaciones',
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_code', models.CharField(max_length=20, null=True, unique=True, verbose_name='Codigo camara de comercio')),
                ('abbreviation', models.CharField(max_length=15, null=True, unique=True, verbose_name='Nomenclatura')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(db_default=True, default=True, verbose_name='Estado Activo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Tipo de organización',
                'verbose_name_plural': 'Tipos de organizaciones',
            },
        ),
        migrations.CreateModel(
            name='TaxRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_regime_code', models.CharField(max_length=20, null=True, unique=True, verbose_name='Codigo legal')),
                ('abbreviation', models.CharField(max_length=15, null=True, unique=True, verbose_name='Nomenclatura')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(db_default=True, default=True, verbose_name='Estado Activo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Regimen fiscal',
                'verbose_name_plural': 'Regimenes fiscales',
            },
        ),
        migrations.CreateModel(
            name='TaxResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_responsibility_code', models.CharField(max_length=20, null=True, unique=True, verbose_name='Codigo legal')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(db_default=True, default=True, verbose_name='Estado Activo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Responsabilidad fiscal',
                'verbose_name_plural': 'Responsabilidades fiscales',
            },
        ),
    ]
