# Generated by Django 6.0.3 on 2026-06-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_geography', '0002_alter_city_is_active_alter_country_is_active_and_more'),
        ('admin_legal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código postal')),
                ('legal_name', models.CharField(max_length=200, unique=True, verbose_name='Razón Social')),
                ('trade_name', models.CharField(max_length=200, unique=True, verbose_name='Nombre Comercial')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='Número de identificación')),
                ('verification_digit', models.SmallIntegerField(blank=True, null=True, verbose_name='Dígito de verificación')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('website', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Página Web')),
                ('user_limit', models.PositiveIntegerField(verbose_name='Cantidad de usuarios permitidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('is_paid_up', models.BooleanField(db_default=True, default=True, verbose_name='Pago al dia')),
                ('is_active', models.BooleanField(db_default=True, default=True, verbose_name='Estado activo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.city', verbose_name='Ciudad')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.country', verbose_name='País')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_legal.idtype', verbose_name='Tipo de identificación')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_legal.organizationtype', verbose_name='Tipo de organización')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.state', verbose_name='Departamento')),
                ('tax_regime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_legal.taxregime', verbose_name='Régimen Fiscal')),
                ('tax_responsibilities', models.ManyToManyField(to='admin_legal.taxresponsibility', verbose_name='Responsabilidades Fiscales')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código postal')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('user_limit', models.PositiveIntegerField(verbose_name='Cantidad de usuarios permitidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(db_default=True, default=True, verbose_name='Estado activo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.city', verbose_name='Ciudad')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.country', verbose_name='País')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.state', verbose_name='Departamento')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_companies.company', verbose_name='Compañía')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='LegalRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primer Nombre')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Apellido')),
                ('identification_number', models.CharField(max_length=50, verbose_name='Número del documento')),
                ('verification_digit', models.SmallIntegerField(blank=True, null=True, verbose_name='Dígito de verificación')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Número telefónico')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(db_default=True, default=True, verbose_name='Estado Activo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_geography.country', verbose_name='País')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_legal.idtype', verbose_name='Tipo de identificación')),
            ],
            options={
                'verbose_name': 'Representante legal',
                'verbose_name_plural': 'Representantes legales',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='legal_representative',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admin_companies.legalrepresentative', verbose_name='Representante legal'),
        ),
    ]
